### PR TITLE
Fix issue with autoload of helper

### PR DESCRIPTION
**Pull request by rknaus**
In certain situations the require 'puppet_x/eos/utils/helpers' line results in an error like this: Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/type/eos_user: no such file to load -- puppet_x/eos/utils/helpers at /etc/puppetlabs/code/environments/production/modules/nc_arista_eos/manifests/init.pp:72:3 on node tor1.localdomain
The implemented workaround fixes this.

### CODE REVIEW

**Comment by jerearista** [comment]
Jenkins, test this please

**Comment by jerearista** [comment]
Jenkins, retest this please

**Comment by jerearista** [comment]
Jenkins, retest this please due to rubygem dependency issues

**Comment by jerearista** [comment]
Jenkins, retest this please due to rubygem dependency issues

**Comment by jerearista** [comment]
Jenkins, retest this please due to rubygem dependency issues

**Comment by jerearista** [comment]
Jenkins, retest this please due to rubygem dependency issues

**Comment by jerearista** [comment]
Jenkins, retest this please due to rubygem dependency issues

**Comment by jerearista** [comment]
Jenkins, retest this please due to rubygem dependency issues, picking up 1 more Gemfile update

**Comment by devrobo** [comment]
Thank you for making this change.

**Pull request merged**
