### PR TITLE
portchannel_convergence needs two puppet runs

### PR DESCRIPTION
**Pull request by mmailand**
For a description see  #84 
I am not sure if my solution is the bestway to tackel this issue, but if it is the best way,
please merge

Thanks,
 martin

### CODE REVIEW

**Comment by jerearista** [comment]
Jenkins, ok to test

**Comment by jerearista** [comment]
Jenkins, retest this please

**Comment by devrobo** [comment]
Thank you for creating the issue and suggesting a fix. We want to try to reproduce this problem to understand why the tests are not catching the issue.

**Comment by mmailand** [comment]
Hi devrobo,
is there any progess on this issue? How could I help you?

cherrs,
martin

**Comment by jerearista** [comment]
Martin,  I will make sure to spend some time on this issue within the next week.

**Comment by rknaus** [comment]
I can confirm that this fix solves the issue that two puppet runs are required if a new port-channel with members (mode=active/passive) is created
+1

**Comment by jerearista** [comment]
👍

**Pull request merged**
