### PR TITLE
Created eos_vrrp type

### PR DESCRIPTION
**Pull request by devrobo**
Added a shared method to convert keys to strings or symbols.
Noticed eos_bgp_config test was not checking ensure in provider unit test.

### CODE REVIEW

**Comment by jerearista** [comment]
test this please

**Comment by devrobo** [comment]
retest this please

**Comment by websitescenes** [comment]
retest this please

**Comment by websitescenes** [comment]
retest this please

**Comment by jerearista** [comment]
retest this please

**Pull request merged**
